server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true


  mustache:
    prefix: classpath:/templates/
    suffix: .html
    charset: UTF-8

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 957359987657-1sm9jgkqtg40peetcah8n6sl1o7bisus.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          